require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'SampleReactNative' do
	# Comment the next line if you don't want to use dynamic frameworks
	use_frameworks!

	config = use_native_modules!

	use_react_native!(:path => config["reactNativePath"])

	pod ‘unicocheck-ios’, '2.3.5'

	target 'SampleReactNativeTests' do
		inherit! :complete
	# Pods for testing
	end
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		if ["CryptoSwift", "JOSESwift"].include? target.name
			target.build_configurations.each do |config|
				config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
			end
		end
	end
end

# Enables Flipper.
#
# Note that if you have use_frameworks! enabled, Flipper will not work and
# you should disable these next few lines.
#
# use_flipper!
#     post_install do |installer|
#         flipper_post_install(installer)
# end